### PR TITLE
Added json serializer abstraction

### PR DESCRIPTION
**Pull request by marceloverdijk**
PR for #6

### CODE REVIEW

**Comment by jsdevel** [comment]
wow!  i need this!  @andimarek any chance you can merge/publish this soon?

**Review by andimarek — APPROVED** [review]
Thanks @marceloverdijk.

**Comment by jsdevel** [comment]
@andimarek when will 2.0 be released?

**Comment by alexkeshav** [comment]
When is release of this version 2 , Lot of interesting functionality in this bunch  :)

**Pull request merged**
