### PR TITLE
build(*): upgrade to GraphQL Java 16.2

### PR DESCRIPTION
**Pull request by aoudiamoncef**
Hi @bbakerman @andimarek,
I'm waiting for your feedback.

Thanks

### CODE REVIEW

**Review by Sounie — COMMENTED** [review]
This upgrade makes sense to me, though with the delay in having it approved it may be worthwhile giving springVersion and springBootVersion a minor release update to pick up the latest fixes and transient dependency upgrades.

**Comment by aoudiamoncef** [comment]
Hi @Sounie

All is updated, cc @bbakerman

Thanks

**Comment by mjbyrnes4664** [comment]
Any update on this? Bunch of people are waiting for the changes in graphql-java v16

**Comment by andimarek** [comment]
This project is now archived in favor of the official [Spring GraphQL](https://github.com/graphql-java/graphql-java-spring) integration.

**Pull request closed without merging**
