### PR TITLE
Updated to v15 graphql.Assert API

### PR DESCRIPTION
**Pull request by andue**
this updates `graphqlJavaVersion` to 15.0 and fixes the assert api changes from https://github.com/graphql-java/graphql-java-spring/issues/31

### CODE REVIEW

**Review by hinterdupfinger — APPROVED** [review]
👍

**Review by erikhh — APPROVED** [review]

**Comment by nikolayandr** [comment]
Guys please approve this MR, it really stops from upgrading to java-graphql#15, thanks

**Comment by kosmos** [comment]
👍

**Comment by andimarek** [comment]
sure ... thanks for putting up @andue

**Comment by nikolayandr** [comment]
@andimarek will these changes available on https://mvnrepository.com/artifact/com.graphql-java/graphql-java-spring-boot-starter-webmvc ? Thanks

**Comment by nikolayandr** [comment]
@erikhh @hinterdupfinger @andimarek Are there any plans to publish new library version in the nearest time? Thanks

**Comment by erikhh** [comment]
@nikolayandr If I could I would,  I'm waiting for this just like you. I'm keeping my code on v14 in the mean time.

**Comment by andimarek** [comment]
I will try to release a new version next week.

**Comment by andimarek** [comment]
We published a new version https://github.com/graphql-java/graphql-java-spring/releases/tag/v2.0

**Pull request merged**
