### PR TITLE
#4 Add support for application/graphql content type and post query params

### PR DESCRIPTION
**Pull request by marceloverdijk**
This is PR is for issue #4. Please feel free to re-author where needed.

### CODE REVIEW

**Comment by marceloverdijk** [comment]
Hi @andimarek is there something I can do to get this forward and maybe push a `1.1` release?

**Comment by jsdevel** [comment]
@andimarek my team is evaluating whether or not we should use this package.  are you still maintaining it?

**Comment by andimarek** [comment]
@jsdevel yes it is still maintained, but did not have enough time recently. I plan to pick up a few things as soon as I can.

**Review by andimarek — CHANGES_REQUESTED** [review]
The PR looks great overall @marceloverdijk.

But I think we should add explicit tests for the post requests with  "query" query string parameter.

**Comment by marceloverdijk** [comment]
@andimarek Yes indeed. I have these test already in Micronaut-GraphQL: https://github.com/micronaut-projects/micronaut-graphql/blob/master/graphql/src/test/groovy/io/micronaut/configuration/graphql/GraphQLControllerSpec.groovy

I will "copy" them over.

**Comment by marceloverdijk** [comment]
@andimarek I have added the missing tests. 

If possible, could you merge this one before I start working on https://github.com/graphql-java/graphql-java-spring/issues/6 ? Otherwise I expect merge conflicts later...

**Comment by andimarek** [comment]
@marceloverdijk merged ... thanks again

**Comment by marceloverdijk** [comment]
@andimarek thx for merging, #4 can be closed now as well.

**Pull request merged**
